a715/a715/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('general.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

a715/general/urls.py
from django.urls import path
from .views import home, detail, catalog

app_name = 'general'
urlpatterns = [
    path('', home, name='home'),
    path('flower/<int:flower_id>/', detail, name='detail'),
    path('catalog/', catalog, name='catalog')
]

a715/general/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField(default='')
    price = models.FloatField(default=0)
    is_available = models.BooleanField(default=False)
    photo = models.ImageField(upload_to='photos')

    def __str__(self):
        return f'{self.name} за {self.price}р'

a715/general/views.py
from django.shortcuts import render
from .models import Product
from django.db.models.functions import Trim


def home(request):
    flowers = Product.objects.order_by('-id')[:3]
    context = {
        'flowers': flowers
    }
    return render(request, 'pages/index.html', context)


def detail(request, flower_id):
    flowers = Product.objects.get(id=flower_id)
    context = {
        'flowers': flowers
    }
    return render(request, 'pages/detail.html', context)


def catalog(request):
    flowers = Product.objects.order_by('-id')
    context = {
        'flowers': flowers
    }
    return render(request, 'pages/catalog.html', context)

a715/templates/base/base.html
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Internet shop</title>
</head>
<body>
<div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
        <span class="fs-4">Цветочный магазин</span>
      </a>

      <ul class="nav nav-pills">
        <li class="nav-item"><a href="{% url 'general:home' %}" class="nav-link" aria-current="page">Главная</a></li>
        <li class="nav-item"><a href="{% url 'general:catalog' %}" class="nav-link">Каталог</a></li>
      </ul>
    </header>
</div>
<div class="container">{% block content %}

{% endblock content %}
</div>

</body>
</html>

a715/templates/pages/catalog.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<section>
    <div class="album py-5 bg-body-tertiary">
    <div class="">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for flower in flowers %}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ flower.photo.url }}">
            <div class="card-body">
              <p class="card-text">{{ flower.name }} | {{ flower.price }}Р</p>
                <small class="text-body-secondary">{{ flower.description }}</small>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'general:detail' flower.id %}"><button type="button" class="btn btn-sm btn-outline-secondary">Посмотреть</button></a>
                </div>
              </div>
            </div>
          </div>
        </div>
          {% endfor %}
      </div>
    </div>
  </div>
</section>
{% endblock %}

a715/templates/pages/detail.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<div class=" my-5">
  <div class="p-5 text-center bg-body-tertiary rounded-3">
      <img src="{{ flowers.photo.url }}" alt="">
    <h1 class="text-body-emphasis">{{ flowers.name }} | {{ flowers.price }}Р</h1>
    <p class="col-lg-8 mx-auto fs-5 text-muted">
        {{ flowers.description }}
    </p>
    <div class="d-inline-flex gap-2 mb-5">
      <button class="d-inline-flex align-items-center btn btn-primary btn-lg px-4 rounded-pill" type="button">
        Купить
      </button>
    </div>
  </div>
</div>
{% endblock %}

a715/templates/pages/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<section>
    <div class="my-5">
  <div class="p-5 text-center bg-body-tertiary rounded-3">
    <h1 class="text-body-emphasis">интернет магазин цветов</h1>
    <p class="col-lg-8 mx-auto fs-5 text-muted">
        Мы дарим радость нашим покупателям! Ведь наши цветы самые лучшие.
    </p>
  </div>
</div>
</section>

<section>
    <div class="album py-5 bg-body-tertiary">
    <div class="">
        <h1 class="text-center">Наши лучшие цветы</h1>

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for flower in flowers %}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ flower.photo.url }}">
            <div class="card-body">
              <p class="card-text">{{ flower.name }} | {{ flower.price }}Р</p>
                <small class="text-body-secondary">{{ flower.description }}</small>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'general:detail' flower.id %}"><button type="button" class="btn btn-sm btn-outline-secondary">Посмотреть</button></a>
                </div>
              </div>
            </div>
          </div>
        </div>
          {% endfor %}
      </div>
    </div>
  </div>
</section>
{% endblock %}